sudo: required
dist: trusty
language: c
compiler: gcc
branches:
  only:
  - master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc
  - sudo apt-get install apache2-dev
  - sudo apt-get install libphp5-embed 
  - sudo apt-get install php5-dev
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install autoconf 
  - dpkg -L libmemcached-dev
install:
  - autoconf -f 
  #- automake -f 
  - ./configure --with-apxs=/usr/bin/apxs --with-libmemcached=/usr || cat config.log 

script:
  - make
matrix:
  fast_finish: false
  
