title: AuthMemCookie Apache Module
description: "&quot;Auth MemCookie&quot; is an Apache v2 Authentication and authorization </br > modules based on &quot;cookie&quot; Authentication mechanism"
google_analytics: UA-3441258-7
show_downloads: true
theme: jekyll-theme-cayman
keywords: Apache, module, authentication, authorization, sso, memcached, simplesaml, opensso
gems:
  - jekyll-mentions
plugins:
  - jekyll-sitemap
