title: Apache-authmemcookie-module
description: "&quot;Auth MemCookie&quot; is an Apache v2 Authentication and authorization </br > modules based on &quot;cookie&quot; Authentication mechanism"
google_analytics: UA-3441258-7
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
