version: 2
jobs:
    build-debian-latest:
      docker:
        - image: debian:latest
      steps:
        - checkout
        - run:
            name: pre 
            command: apt-get update && apt-get install -y gcc apache2 apache2-dev memcached libmemcached libmemcached-dev autoconf
        - run:
            name: libmemcached version
            command: dpkg -s libmemcached-dev && dpkg -L libmemcached-dev
        - run:
            name: apache2 version
            command: dpkg -s apache2 && dpkg -L apache2-dev && dpkg -L apache2
        - run:
            name: autogen
            command: autoconf -f
        - run:
            name: autoconf
            command: ./configure --with-apxs=/usr/bin/apxs --with-libmemcached=/usr && cat mod_auth_memcookie.h || cat config.log  
        - run:
            name: build
            command: make  && ls -al .libs/mod_auth_memcookie.so
        - run:
            name: install
            command: make install && apache2ctl configtest
    build-ubuntu-14:
      docker:
        - image: ubuntu:14.04
      steps:
        - checkout
        - run:
            name: pre 
            command: apt-get update && apt-get install -y gcc apache2 apache2-dev memcached libmemcached libmemcached-dev autoconf
        - run:
            name: libmemcached version
            command: dpkg -s libmemcached-dev && dpkg -L libmemcached-dev
        - run:
            name: apache2 version
            command: dpkg -s apache2 && dpkg -L apache2-dev && dpkg -L apache2
        - run:
            name: autogen
            command: autoconf -f
        - run:
            name: autoconf
            command: ./configure --with-apxs=/usr/bin/apxs --with-libmemcached=/usr && cat mod_auth_memcookie.h || cat config.log  
        - run:
            name: build
            command: make  && ls -al .libs/mod_auth_memcookie.so
        - run:
            name: install
            command: make install && apache2ctl configtest 
 
workflows:
  version: 2
  multiple_os_build:
    jobs:
      - build-debian-latest
      - build-ubuntu-14
